CREATE TABLE MAIN_CATE (
    CAT_ID INTEGER PRIMARY KEY,
    NAME VARCHAR2(50));

CREATE TABLE BUSINESS (
    BUSINESS_ID VARCHAR2(50) PRIMARY KEY,
    FULL_ADDRESS VARCHAR2(150),
    ---HOURS VARCHAR2(50),
    OPEN INTEGER,
    CATEGORIES INTEGER,
    CITY VARCHAR2(50),
    STATE VARCHAR2(50),
    LATITUDE NUMBER,
    LONGITUDE NUMBER,
    REVIEW_COUNT INTEGER,
    NAME VARCHAR2(100),
    --NEIGHBORHOODS VARCHAR2(50),
    STARS NUMBER,
    --ATTRIBUTES VARCHAR2(50),
    TYPE VARCHAR2(50),
    FOREIGN KEY (CATEGORIES) REFERENCES MAIN_CATE (CAT_ID) ON DELETE SET NULL);
    
CREATE TABLE SUB_CATE (
    BUSINESS_ID VARCHAR2(50),
    NAME VARCHAR2(50),
    PRIMARY KEY(BUSINESS_ID, NAME),
    FOREIGN KEY (BUSINESS_ID) REFERENCES BUSINESS (BUSINESS_ID));
    
CREATE TABLE HOURS (
    BUSINESS_ID VARCHAR2(50),
    WEEK VARCHAR2(25),
    OPEN VARCHAR2(20),
    CLOSE VARCHAR2(20),
    PRIMARY KEY (BUSINESS_ID, WEEK),
    FOREIGN KEY (BUSINESS_ID) REFERENCES BUSINESS (BUSINESS_ID) ON DELETE CASCADE);

CREATE TABLE USERS (
    USER_ID VARCHAR2(50) PRIMARY KEY,
    YELPING_SINCE DATE,
    ---VOTES
    REVIEW_COUNT INTEGER,
    NAME VARCHAR2(50),
    ---FRIENDS
    FANS INTEGER,
    AVERAGE_STARS NUMBER,
    TYPE VARCHAR2(40)
    --COMPLIMENTS VARCHAR2(100)
    --ELITE
);

CREATE TABLE REVIEWS (
    --VOTES
    REVIEW_ID VARCHAR2(50) PRIMARY KEY,
    USER_ID VARCHAR2(50),
    STARS NUMBER,
    REVIEW_DATE DATE,
    ---TEXT VARCHAR2(1500),
    TYPE VARCHAR2(50),
    BUSINESS_ID VARCHAR2(50),
    FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (BUSINESS_ID) REFERENCES BUSINESS (BUSINESS_ID) ON DELETE CASCADE);
    
CREATE TABLE REV_VOTES (
    REVIEW_ID VARCHAR2(50),
    TYPE VARCHAR2(10), 
    COUNT INTEGER,
    PRIMARY KEY (REVIEW_ID, TYPE),
    FOREIGN KEY (REVIEW_ID) REFERENCES REVIEWS (REVIEW_ID) ON DELETE CASCADE);


CREATE TABLE USER_VOTES (
    USER_ID VARCHAR2(50),
    TYPE VARCHAR2(10),
    COUNT INTEGER,
    PRIMARY KEY (USER_ID, TYPE),
    FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID) ON DELETE CASCADE);
    
CREATE TABLE USER_FRIENDS (
    USER_ID VARCHAR2(50),
    FRIENDS VARCHAR2(50),
    PRIMARY KEY (USER_ID, FRIENDS),
    FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID) ON DELETE CASCADE);
    
CREATE TABLE CHECKIN (
    BUSINESS_ID VARCHAR2(50),
    CHECKIN_INFO VARCHAR2(10),--need mod
    TYPE VARCHAR2(30),
    PRIMARY KEY (BUSINESS_ID, CHECKIN_INFO),
    FOREIGN KEY (BUSINESS_ID) REFERENCES BUSINESS (BUSINESS_ID) ON DELETE CASCADE);
    