DROP TABLE CHECKIN;
DROP TABLE USER_FRIENDS;
--DROP TABLE USER_VOTES;
--DROP TABLE REV_VOTES;
DROP TABLE REVIEWS;
DROP TABLE USERS;
DROP TABLE HOURS;
DROP TABLE SUB_CATE;
DROP TABLE BUSINESS;
DROP TABLE MAIN_CATE;





